const fabrics = [
	{
		id: 0,
		name: "BlueBlack African Print v1",
		img: "/products/fb_1.jpg",
		price: 999.99,
		isNew: true,
		category: "fabrics",
	},
	{
		id: 1,
		name: "Deep Blue Print v1",
		img: "/products/fb_2.jpg",
		price: 799.99,
		isNew: true,
		category: "fabrics",
	},
	{
		id: 2,
		name: "Light Blue Print v1",
		img: "/products/fb_3.jpg",
		price: 500.99,
		isNew: true,
		category: "fabrics",
	},
	{
		id: 3,
		name: "Light Yellow African v1",
		img: "/products/fb_4.jpg",
		price: 899.99,
		isNew: false,
		category: "fabrics",
	},
	{
		id: 4,
		name: "Silver Duku v1",
		img: "/products/dk_9.jpg",
		price: 89.99,
		isNew: true,
		category: "duku",
	},
	{
		id: 5,
		name: "WhiteBlack Local Print v1",
		img: "/products/fb_5.jpg",
		price: 1400.99,
		isNew: true,
		category: "fabrics",
	},
	{
		id: 6,
		name: "LightBlue Duku v1",
		img: "/products/dk_2.jpg",
		price: 89.99,
		isNew: true,
		category: "duku",
	},
	{
		id: 7,
		name: "Deep Blue Print v2",
		img: "/products/fb_6.jpg",
		price: 50.99,
		isNew: false,
		category: "fabrics",
	},
	{
		id: 8,
		name: "WhiteBlack Local Print v2",
		img: "/products/fb_7.jpg",
		price: 999.99,
		isNew: false,
		category: "fabrics",
	},
	{
		id: 9,
		name: "Light Yellow African v2",
		img: "/products/fb_8.jpg",
		price: 599.99,
		isNew: false,
		category: "fabrics",
	},
	{
		id: 10,
		name: "YellowBlue Traditional Print v1",
		img: "/products/fb_9.jpg",
		price: 799.99,
		isNew: true,
		category: "fabrics",
	},
	{
		id: 11,
		name: "Mauve Dot Print v1",
		img: "/products/fb_10.jpg",
		price: 399.99,
		isNew: true,
		category: "fabrics",
	},
	{
		id: 12,
		name: "Green Yellow African Mix v1",
		img: "/products/fb_11.jpg",
		price: 799.99,
		isNew: false,
		category: "fabrics",
	},
	{
		id: 13,
		name: "YellowBlue Traditional Print v2",
		img: "/products/fb_12.jpg",
		price: 299.99,
		isNew: false,
		category: "fabrics",
	},
	{
		id: 14,
		name: "Yellow Fabric Variant v1",
		img: "/products/fb_13.jpg",
		price: 899.99,
		isNew: true,
		category: "fabrics",
	},
	{
		id: 15,
		name: "White Traditional Mix v1",
		img: "/products/fb_14.jpg",
		price: 659.99,
		isNew: false,
		category: "fabrics",
	},
	{
		id: 16,
		name: "Red Tie&Die Print v1",
		img: "/products/fb_15.jpg",
		price: 799.99,
		isNew: true,
		category: "fabrics",
	},
	{
		id: 17,
		name: "YellowBlue Traditional Print v3",
		img: "/products/fb_27.jpg",
		price: 1099.99,
		isNew: false,
		category: "fabrics",
	},
	{
		id: 18,
		name: "Gold Duku v1",
		img: "/products/dk_3.jpg",
		price: 119.99,
		isNew: false,
		category: "duku",
	},
	{
		id: 19,
		name: "Gold Duku v2",
		img: "/products/dk_17.jpg",
		price: 100.99,
		isNew: true,
		category: "duku",
	},
	{
		id: 20,
		name: "RBY African Print v1",
		img: "/products/fb_26.jpg",
		price: 799.99,
		isNew: false,
		category: "fabrics",
	},
	{
		id: 21,
		name: "RedSilver Duku v1",
		img: "/products/dk_11.jpg",
		price: 79.99,
		isNew: true,
		category: "duku",
	},
	{
		id: 22,
		name: "Gold Duku v3",
		img: "/products/dk_7.jpg",
		price: 79.99,
		isNew: false,
		category: "duku",
	},
	{
		id: 23,
		name: "Gold Duku v4",
		img: "/products/dk_8.jpg",
		price: 89.99,
		isNew: false,
		category: "duku",
	},
];

export default fabrics;
